main:
  - name: Home
    url: '#about'
    weight: 10
  - name: Talks
    url: '#talks'
    weight: 20
  - name: Posts
    url: '#posts'
    weight: 30
  - name: Projects
    url: '#projects'
    weight: 40
  - name: Publications
    url: '#featured'
    weight: 50
  - name: Contact
    url: '#contact'
    weight: 60
  - name: Resume
    url: files/resume.pdf
    weight: 70

